2019-06-15 10:26:38 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: spiderframe)
2019-06-15 10:26:38 [scrapy.utils.log] INFO: Versions: lxml 4.3.3.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 18.9.0, Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019), cryptography 2.6.1, Platform Windows-7-6.1.7601-SP1
2019-06-15 10:26:38 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'spiderframe', 'DOWNLOAD_DELAY': 0.3, 'LOG_FILE': 'log/scrapy_2019615.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'spiderframe.spiders', 'SPIDER_MODULES': ['spiderframe.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
2019-06-15 10:26:38 [scrapy.extensions.telnet] INFO: Telnet Password: 87816f3eba653c73
2019-06-15 10:26:38 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-06-15 10:26:39 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-06-15 10:26:39 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-06-15 10:26:39 [scrapy.middleware] INFO: Enabled item pipelines:
['spiderframe.pipelines.SpiderframePipeline',
 'spiderframe.pipelines.RedisPipeline',
 'spiderframe.pipelines.MySQLPipeline',
 'spiderframe.pipelines.ImagePipeline']
2019-06-15 10:26:39 [scrapy.core.engine] INFO: Spider opened
2019-06-15 10:26:49 [scrapy.core.engine] INFO: Closing spider (shutdown)
2019-06-15 10:26:49 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\scrapy\crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '123.56.11.156' (timed out)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\datatang\spiderframe\spiderframe\pipelines.py", line 59, in close_spider
    self.db_conn.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
2019-06-15 10:26:49 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'shutdown',
 'finish_time': datetime.datetime(2019, 6, 15, 2, 26, 49, 214400),
 'log_count/ERROR': 1,
 'log_count/INFO': 7}
2019-06-15 10:26:49 [scrapy.core.engine] INFO: Spider closed (shutdown)
2019-06-15 10:26:49 [twisted] CRITICAL: Unhandled error in Deferred:
2019-06-15 10:26:49 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\datatang\venv\lib\site-packages\scrapy\crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '123.56.11.156' (timed out)")
2019-06-15 15:43:44 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: spiderframe)
2019-06-15 15:43:44 [scrapy.utils.log] INFO: Versions: lxml 4.3.3.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 18.9.0, Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019), cryptography 2.6.1, Platform Windows-7-6.1.7601-SP1
2019-06-15 15:43:44 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'spiderframe', 'DOWNLOAD_DELAY': 0.3, 'LOG_FILE': 'log/scrapy_2019615.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'spiderframe.spiders', 'SPIDER_MODULES': ['spiderframe.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
2019-06-15 15:43:46 [scrapy.extensions.telnet] INFO: Telnet Password: b72769520af68dce
2019-06-15 15:43:47 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-06-15 15:43:49 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-06-15 15:43:49 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-06-15 15:43:50 [scrapy.middleware] INFO: Enabled item pipelines:
['spiderframe.pipelines.SpiderframePipeline',
 'spiderframe.pipelines.RedisPipeline',
 'spiderframe.pipelines.MySQLPipeline',
 'spiderframe.pipelines.ImagePipeline']
2019-06-15 15:43:50 [scrapy.core.engine] INFO: Spider opened
2019-06-15 15:44:00 [scrapy.core.engine] INFO: Closing spider (shutdown)
2019-06-15 15:44:00 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\scrapy\crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '123.56.11.156' (timed out)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "D:\datatang\spiderframe\spiderframe\pipelines.py", line 59, in close_spider
    self.db_conn.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
2019-06-15 15:44:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'shutdown',
 'finish_time': datetime.datetime(2019, 6, 15, 7, 44, 1, 5600),
 'log_count/ERROR': 1,
 'log_count/INFO': 7}
2019-06-15 15:44:01 [scrapy.core.engine] INFO: Spider closed (shutdown)
2019-06-15 15:44:01 [twisted] CRITICAL: Unhandled error in Deferred:
2019-06-15 15:44:01 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\datatang\venv\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\datatang\venv\lib\site-packages\scrapy\crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '123.56.11.156' (timed out)")
